language: rust
cache: cargo
install:
- command -v mdbook >/dev/null 2>&1 || cargo install --debug mdbook --no-default-features --features search
script:
- mdbook build
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: book
  on:
    branch: master
env:
  global:
    secure: 5LGxRyeIjxcqJ4Acs51XpHzveRvOKZR3rW4CGTk+xETX8QkrP6jxUP0bQ4AXgcfMnBSO0TcNbKbk4tz48MB+y7hK75OJU+v4sor7EDHBLKFslDJWNVeOBZF3G2zaLKhAeEX5VN2H52UnbGSzhDX+Bx6SxmUP3bEsQxOBk4MLPnDuDe+dglX24kridaR7UOBjjvDi2xCDFBeIZZZASfiWDU91MZxI/amlW2X6MnDFg5/lBa/mC/1n+cBlyW+UN9qmG/1UNU3L1GKjjNqubkz7bR71eFAue2+Eo/PM3T3oKAtj4noHBc7j94AkQDMxvKS9AxkD6TVhzKDc/iZLwH26iQKpoZ7yx3/z1BEZcpSl7xw9bY/D02pgDCdGonwge1KIht6fl15MdLBbjq1msMm1oqLNLpbB+DvaXuiw7ou4ZjRIyM3IiFFUPAew+E9a1HwVVY767BM0FDPhJP/qf+itgul4YgyIV1yulJsJHGNJNdQ84tw4raPheM8B0Aa71g3gp1NR1z6sZ+35S+XVKqtoanh4nFtHZbA9UVIbSYRQk4ZPv69q+vugzBGi835tEqEPN2xgzc0EVWz0F1rfuKuWUuWhriL3xY7whhoKyySW0VcQie22VVQGNWS54WM882OsRtbmaAfqLtpAbV4B1Iz9WfzwJ/1/lnasUmkmvGXPaiI=
